//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityCourseAndResultManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public int CourseId { get; set; }
        public string CourseCode { get; set; }
        public string CourseName { get; set; }
        public string CourseCredit { get; set; }
        public string CourseDescription { get; set; }
        public int DepartmentId { get; set; }
        public int SemisterId { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Semister Semister { get; set; }
    }
}
